

version: '3.8'

services:
  range-wave-rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5677:5672"
      - "15677:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - mongo-cluster
 


  express-range-wave:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-app-dev
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      range-wave-rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    external: true
