version: '3.8'

services:
  redis-range-wave:
    image: redis
    container_name: range-wave-redis-queue
    ports:
     - "6378:6379"
    networks:
      - mongo-cluster

  express-range-wave:
    build: .
    container_name: range-wave-express-app
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - redis-range-wave
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # or `npm run start` depending on your setup
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    external: true